// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9k_DlKHaVVg8TFBkaYN23Vw-y0tQ-5Zg',
    appId: '1:555939491119:web:bda8e37d6bf2936ccd85da',
    messagingSenderId: '555939491119',
    projectId: 'shit-i-need-to-do-today',
    authDomain: 'shit-i-need-to-do-today.firebaseapp.com',
    storageBucket: 'shit-i-need-to-do-today.firebasestorage.app',
    measurementId: 'G-S5DF2GN2VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9hsilT0PK26Mgs71AAHZnp6skSp-TWI8',
    appId: '1:555939491119:android:b30850786d708cf5cd85da',
    messagingSenderId: '555939491119',
    projectId: 'shit-i-need-to-do-today',
    storageBucket: 'shit-i-need-to-do-today.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMO3X_cvvav9yAHKEFZYnZzmgGewCDcI0',
    appId: '1:555939491119:ios:887aa3f92e0cbe0ccd85da',
    messagingSenderId: '555939491119',
    projectId: 'shit-i-need-to-do-today',
    storageBucket: 'shit-i-need-to-do-today.firebasestorage.app',
    iosBundleId: 'io.agilepixel.snitd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMO3X_cvvav9yAHKEFZYnZzmgGewCDcI0',
    appId: '1:555939491119:ios:887aa3f92e0cbe0ccd85da',
    messagingSenderId: '555939491119',
    projectId: 'shit-i-need-to-do-today',
    storageBucket: 'shit-i-need-to-do-today.firebasestorage.app',
    iosBundleId: 'io.agilepixel.snitd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9k_DlKHaVVg8TFBkaYN23Vw-y0tQ-5Zg',
    appId: '1:555939491119:web:e8f1442fcb9053fecd85da',
    messagingSenderId: '555939491119',
    projectId: 'shit-i-need-to-do-today',
    authDomain: 'shit-i-need-to-do-today.firebaseapp.com',
    storageBucket: 'shit-i-need-to-do-today.firebasestorage.app',
    measurementId: 'G-9NRGMMXPB4',
  );
}
